name: Pull request title

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          filter: tree:0
          fetch-depth: 1

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.4.2

      - run: bun install --no-cache --frozen-lockfile
      - name: Validate title
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: printf '%s\n' "$PR_TITLE" | bunx commitlint --verbose
